In [1]:
import torch
X = torch.Tensor(2, 3)
X

tensor([[5.9517e+31, 4.5600e-41, 5.9517e+31],
        [4.5600e-41, 2.4106e+31, 4.5600e-41]])

In [2]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
x_tensor = torch.tensor(data=[2., 3.], requires_grad=True)
x_tensor

tensor([2., 3.], requires_grad=True)

In [4]:
import torch

x = torch.tensor(data=[2., 3.], requires_grad=True)
y = x**2
z = 2*y + 3

target = torch.tensor([3., 4.])
loss = torch.sum(torch.abs(z-target))
loss.backward()

print(x.grad, y.grad, z.grad)


tensor([ 8., 12.]) None None


<ipython-input-4-66c83cd0bbcd>:11: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(x.grad, y.grad, z.grad)


In [5]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

In [6]:
num_data = 100
num_epoch = 500

x = init.uniform_(torch.Tensor(num_data, 1), -10, 10)
noise = init.normal_(torch.FloatTensor(num_data, 1), std=1)
y = 2*x+3
y_noise = y+noise

In [7]:
model = nn.Linear(1 ,1)
loss_func = nn.L1Loss()

In [8]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [9]:
from tqdm import tqdm

In [14]:
label = y_noise
for i in tqdm(range(num_epoch)):
    optimizer.zero_grad()
    output = model(x)
    
    loss = loss_func(output, label)
    loss.backward()
    optimizer.step()
    
    if i % 10 == 0:
        print(loss.data)
        param_list = list(model.parameters())
        print(param_list[0].item(), param_list[1].item())
        

100%|██████████| 500/500 [00:00<00:00, 5695.47it/s]

tensor(0.8629)
2.041766405105591 2.931079387664795
tensor(0.8630)
2.040358304977417 2.931079387664795
tensor(0.8628)
2.042217493057251 2.931079387664795
tensor(0.8628)
2.042591094970703 2.9308793544769287
tensor(0.8630)
2.0411829948425293 2.9308793544769287
tensor(0.8629)
2.0397748947143555 2.9308793544769287
tensor(0.8629)
2.0416340827941895 2.9308793544769287
tensor(0.8630)
2.0402259826660156 2.9308793544769287
tensor(0.8629)
2.0420851707458496 2.9308793544769287
tensor(0.8630)
2.040677070617676 2.9308793544769287
tensor(0.8628)
2.0425362586975098 2.9308793544769287
tensor(0.8630)
2.041128158569336 2.9308793544769287
tensor(0.8629)
2.039720058441162 2.9308793544769287
tensor(0.8629)
2.041579246520996 2.9308793544769287
tensor(0.8629)
2.0401711463928223 2.9308793544769287
tensor(0.8629)
2.0420303344726562 2.9308793544769287
tensor(0.8630)
2.0406222343444824 2.9308793544769287
tensor(0.8628)
2.0424814224243164 2.9308793544769287
tensor(0.8630)
2.0410733222961426 2.9308793544769287
tens