# Numpy

- 일반 List에 비해 빠르고, 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리를 지원
- 선형대수와 관련된 다양한 기능을 제공
- C, C++, 포트란 등의 언어와 통합 개발 가능

In [23]:
import numpy as np

### Array creation

파이썬은 Dynamic Typing으로 실행시점에 data type을 결정.
즉, 하나의 리스트에 다양한 데이터 타입이 들어갈 수 있다.
그러나 Numpy는 Dynamic Typing을 지원하지 않아서 속도가 빠르며,
data type 을 하나로 통일 해야한다.

In [24]:
arr = np.array(["1", "4", 5, 8], float)

# numpy.float64메모리 공간의 크기를 64 bit 로 설정
arr, type(arr[0])

(array([1., 4., 5., 8.]), numpy.float64)

In [25]:
# 모양, 데이터 타입
arr.shape, arr.dtype

((4,), dtype('float64'))

In [26]:
# 차원 개수, 원소의 총 개수
arr.ndim, arr.size

(1, 4)

### Reshape

In [32]:
arr = np.array([[1, 2, 3, 4], [1, 2, 5, 8]])
arr.shape

(2, 4)

In [33]:
arr.reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [34]:
arr.reshape(8,).shape

(8,)

In [38]:
# to 2차원
arr.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

In [40]:
# to 1차원
arr.flatten()

array([1, 2, 3, 4, 1, 2, 5, 8])

In [43]:
arr = arr.reshape(2, 2, 2)
arr

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [44]:
arr[0, 0], arr[0][0]

(array([1, 2]), array([1, 2]))

### Numpy 배열 생성

- arange
- ones
- zeros
- empty
- ones_like (shape 복사)
- identity (단위행렬)
- eyes (대각선이 1인 행렬)
- random sampling

In [64]:
np.arange(10).reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [66]:
np.zeros(shape=(10, ), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [67]:
np.ones(shape=(10, ), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [68]:
np.empty(shape=(10, ), dtype=np.int8)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [69]:
arr= np.arange(30).reshape(-1, 6)
np.ones_like(arr)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [70]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [72]:
np.eye(N=3, M=5, dtype=np.int8)     # k -> start index

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [74]:
# 대각 행렬의 값을 추출
arr = np.arange(9).reshape(3, 3)
np.diag(arr)    # k -> start index

array([0, 4, 8])

In [78]:
# 균등분포
np.random.uniform(0, 1, 10).reshape(2, 5)

array([[0.89420085, 0.15623141, 0.79639954, 0.15678867, 0.04138382],
       [0.82226602, 0.97049594, 0.63818646, 0.79597857, 0.28329939]])

In [79]:
# 정규분포
np.random.normal(0, 1, 10).reshape(2, 5)

array([[-1.14569091,  1.45835771, -0.3892437 , -2.2519947 ,  1.20626925],
       [ 0.25392655,  0.72156842,  0.41982118,  0.68076908, -0.44844239]])

In [82]:
# 합
arr, arr.sum()

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 36)