# Vector

- 벡터는 공간에서 한 점을 나타낸다.
- 벡터는 원점으로부터 상대적 위치를 표현한다.
- 벡터에 숫자를 곱해주면 길이만 변한다. (0보다 작으면 반대방향)

In [ ]:
import numpy as np

In [2]:
x = np.array([1, 7, 2])
y = np.array([5, 2, 1])

In [3]:
x + y

array([6, 9, 3])

In [4]:
x - y

array([-4,  5,  1])

In [5]:
x * y

array([ 5, 14,  2])

In [7]:
def l1_norm(x):
    x_norm = np.sum(np.abs(x))
    return x_norm

def l2_norm(x):
    x_norm = x * x
    x_norm = np.sqrt(np.sum(x_norm))
    return x_norm


l1_norm(x), l2_norm(x)

(10, 7.3484692283495345)

In [8]:
def angle(x, y):
    v = np.inner(x, y) / (l2_norm(x) * l2_norm(y))
    theta = np.arccos(v)
    return theta

angle(x, y)

1.0218962578343371